[package]
name = "raytracer"
version = "0.1.0"
authors = ["Martin Rau <martin.rau@tum.de>"]
edition = "2018"

[dependencies]

rayon = "1.5"
nom = "6.1.0"
lazy_static = "1.4.0"

[dev-dependencies]
test-case = "1.1.0"